client/components/Map.js, firebase.json, package-lock.json, package.json, public/index.html, server/firebase.js
=> Weekend firestore

client/components/Map.js, server/index.js
Map: geolocate, style, adminLine toggle
=> Weekend map

public/index.html, public/manifest.json, public/offline.html, public/serviceworker.js
=> Feat: Additional PWA compliance

client/components/Map.js, client/components/PopupBox.js, client/components/StartPage.js, public/style.css
=> Fix: Start Page & PopUp

client/components/SingleLanguage.js
refactor: single lang component to render info from props :D
=> refactor: single lang component to render info from props

client/components/SingleLanguage.js
refactor: basic vocab/phrases on single language component
=> refactor: basic vocab/phrases on single language component

client/components/Map.js, client/components/PopupBox.js
fix popup unchanging state on click without closing out of popup
#77
=> fix popup unchaning state on click witout closing out of popup

client/routes.js, public/style.css
=> style: pull test changes

client/components/SingleLanguage.js, package-lock.json, package.json, public/style.css
style: number of speakers counter animation
=> style: number of speakers animation

client/components/index.js, client/components/user-home.spec.js, client/routes.js
=> Fix: things 4 cd n ci

client/components/Map.js, client/components/PopupBox.js, client/components/SingleLanguage.js, package-lock.json, package.json, public/style.css, webpack.config.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> About to merge

client/components/Map.js, package-lock.json, public/style.css
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> style: loading page

client/components/Map.js, client/components/PopupBox.js, package-lock.json
merging with main (these are the map toggle attempts for adminlines)
=> Test branch

client/components/Map.js, package-lock.json, public/style.css
=> Toggle time

client/components/Map.js, client/components/navbar.js, package-lock.json
=> Bug: workin on the navbar

client/components/Map.js, client/components/PopupBox.js, client/components/SingleLanguage.js, package-lock.json
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
=> New brench

client/components/navbar.js, package-lock.json
=> chore: fixin redundant code

client/components/Map.js
=> Fix: fixed polygonlayer bug

client/components/LogoSVG.js, client/components/StartPage.js, package-lock.json
=> feat: animate mission stment and button on start page

client/components/PopupBox.js, client/components/StartPage.js, package-lock.json, public/style.css
=> New branch

package-lock.json, public/languagePractice.css, public/languagePractice.scss, public/style.css
=> style: adjust media query on language practice
